model:
    arch: fcn8s
data:
    dataset: pascal
    train_split: train_aug
    val_split: val
    img_rows: 'same'
    img_cols: 'same'
    path: /content/drive/My Drive/ColabNotebooks/dataset/VOCdevkit/VOC2012/
    sbd_path: /content/drive/My Drive/ColabNotebooks/dataset/benchmark_RELEASE/
training:
    train_iters: 50000
    batch_size: 1
    val_interval: 500
    n_workers: 4
    print_interval: 100
    optimizer:
        name: 'adam'
        lr: 1.0e-4

    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: 