model:

  arch: fcn8s

data:

  dataset: pascal

  train_split: train_aug

  val_split: val

  img_rows: 'same'

  img_cols: 'same'

  path: C:/20SP/data mining/Project/VOC2012/VOCtrainval_11-May-2012/VOCdevkit/VOC2012

  sbd_path: C:/20SP/data mining/Project/benchmark/benchmark_RELEASE


training:

  train_iters: 10000

  batch_size: 1

  val_interval: 1000

  n_workers: 4

  print_interval: 100

  optimizer:

    name: 'sgd'

    lr: 1.0e-5

  loss:

    name: 'cross_entropy'

    size_average: True

  lr_schedule:

  resume:

