model:

  arch: fcn8s

data:

  dataset: pascal

  train_split: train_aug
  
  val_split: val

  img_rows: 'same'

  img_cols: 'same'

  path: C:/20SP/data mining/Project/VOC2012/VOCtrainval_11-May-2012/VOCdevkit/VOC2012

  sdb_path: C:/20SP/data mining/Project/benchmark/benchmark_RELEASE


training:

  augmentations: {"gamma": AdjustGamma,"hue": AdjustHue,"brightness": AdjustBrightness}
  
  train_iters: 300000

  batch_size: 1

  val_interval: 1000

  n_workers: 16

  print_interval: 50

  optimizer:

    name: 'sgd'

    lr: 1.0e-10

    weight_decay: 0.0005

    momentum: 0.99

  loss:

    name: 'cross_entropy'

    size_average: False

  lr_schedule: {"name":"poly_lr","gamma":0.9,"max_iter":10000}

  resume: C:/20SP/data mining/Project/ckpt/fcn8s_best_model.pkl
